#!/bin/sh

# Gradle start up script for POSIX generated by Gradle

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

OS=`uname`

case "$OS" in
  CYGWIN* | MINGW* )
    IS_WINDOWS=1
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

JAVACMD="java"
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

CLASSPATH=`find "$APP_HOME/gradle/wrapper" -name "gradle-wrapper.jar" -type f 2>/dev/null`

if [ -z "$CLASSPATH" ] ; then
    echo "Downloading Gradle wrapper..."
    mkdir -p "$APP_HOME/gradle/wrapper"
    curl -sL "https://raw.githubusercontent.com/gradle/gradle/v8.5.0/gradle/wrapper/gradle-wrapper.jar" -o "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" 2>/dev/null || \
    curl -sL "https://services.gradle.org/distributions/gradle-8.5-bin.zip" -o /tmp/gradle-8.5.zip 2>&1 >/dev/null && \
    unzip -q -o /tmp/gradle-8.5.zip "gradle-8.5/lib/gradle-wrapper-*.jar" -d /tmp/ 2>/dev/null && \
    cp /tmp/gradle-8.5/lib/gradle-wrapper-*.jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" 2>/dev/null
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
fi

if [ -z "$CLASSPATH" ] ; then
    die "ERROR: Could not find or download gradle-wrapper.jar"
fi

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
